fix: testing husky hook

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,11 +1,14 @@
-#!/bin/bash
-
 echo -e "\033[1;34m──────────────────────────────────────────────\033[0m"
 echo -e "\033[1;32m🔧  Running pre-commit hook...\033[0m"
 echo -e "\033[1;34m──────────────────────────────────────────────\033[0m"
 
 echo -e "\033[1;36m🧹  Linting staged files with lint-staged...\033[0m"
 pnpm exec lint-staged
+
+if [ $? -ne 0 ]; then
+  echo -e "\033[1;31m❌ Lint-staged failed. Aborting commit.\033[0m"
+  exit 1
+fi
 
 echo -e "\033[1;32m✅  Pre-commit checks completed.\033[0m"
 echo -e "\033[1;34m──────────────────────────────────────────────\033[0m"
